# Delete the html (generated by md) from specified folder in project cn

print(getwd())

info <- "Please select:
    1 list directory under project root directory
    2 list file in specified directory
"

isDeleterinRoot <- function (){
  files <- list.files()
  for(f in files){
    cat(f, "\n")
  }
}

isDeleterinRoot()



library(digest)

x <- digest("Hello", algo="md5")
x









